name: Make Docker Image

on:
  push:
    tags:
      - V*

jobs:
  build-image:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/Ver.}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_TOKEN }}

      - name: Docker Build
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ms2-discord-bot:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/ms2-discord-bot:${{ env.RELEASE_VERSION }}
          docker image tag ghcr.io/${{ github.repository_owner }}/ms2-discord-bot:${{ env.RELEASE_VERSION }} ghcr.io/${{ github.repository_owner }}/ms2-discord-bot:latest
          docker push ghcr.io/${{ github.repository_owner }}/ms2-discord-bot:latest